import React from 'react';
import type { Metadata } from 'next';
import './globals.css';

import { CartProvider } from './_context/cart';
import AuthProvider from '../app/_provider/auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Fonts
import { Poppins } from 'next/font/google';
const poppins = Poppins({
  subsets: ['latin-ext'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={poppins.className}>
          <CartProvider>{children}</CartProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
